// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// ItemRemover is an autogenerated mock type for the ItemRemover type
type ItemRemover struct {
	mock.Mock
}

// DeleteItem provides a mock function with given fields: ctx, userID, skuID
func (_m *ItemRemover) DeleteItem(ctx context.Context, userID int64, skuID int64) error {
	ret := _m.Called(ctx, userID, skuID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteItem")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = rf(ctx, userID, skuID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewItemRemover creates a new instance of ItemRemover. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewItemRemover(t interface {
	mock.TestingT
	Cleanup(func())
}) *ItemRemover {
	mock := &ItemRemover{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
