version: "3.8"

services:
  cart:
    container_name: cart
    build:
      context: ./cart
      dockerfile: ./cmd/cart/Dockerfile
    env_file:
      - ./cart/config/docker.env
    ports:
      - "8082:8082"
    restart: always
    healthcheck:
      test: [ "CMD", "wget", "--spider", "--quiet", "cart:8082/healthz" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - backend

networks:
  backend:
    driver: bridge
