// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// CartRemover is an autogenerated mock type for the CartRemover type
type CartRemover struct {
	mock.Mock
}

// DeleteItemsByUserID provides a mock function with given fields: ctx, userID
func (_m *CartRemover) DeleteItemsByUserID(ctx context.Context, userID int64) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteItemsByUserID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCartRemover creates a new instance of CartRemover. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCartRemover(t interface {
	mock.TestingT
	Cleanup(func())
}) *CartRemover {
	mock := &CartRemover{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
