global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'cart'
    static_configs:
      - targets: ['cart:8082']
  - job_name: 'loms'
    static_configs:
      - targets: [ 'loms:8888' ]
